#!/usr/bin/env python3
"""Write REPORT/numbers.tex: LaTeX macros with the high-statistics fixed-PHOKHARA results
(runs fix500k_w1e-4, fix500k_w1e-5, fix500k_w1e-6 under $PHOKHARA_SCRATCH).

  \\HiSigA \\HiSigB \\HiSigC     sigma_MC per w (1e-4, 1e-5, 1e-6)
  \\HiAA   \\HiAB   \\HiAC       A(theta+) per w
  \\HiSlope                      fitted dA(theta+)/dlog10(w)
  \\HiAav \\HiAmav \\HiAvav      w-averaged A(theta+), -A(theta-), -A(thav)
Values of runs with fewer than 300 finished seeds are marked with their seed count.
Also writes RESULTS/fix500k/summary.txt.
"""
import glob, os, re, sys
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
SC = os.path.expanduser("~/scratch/CEEX_PHOKHARA_ANALYSIS/PHOKHARA")
SIG = re.compile(r"sigma_MC \(nbarn\)\s*=\s*(\S+)\s*\+-\s*(\S+)")
RUNS = [("A", -4, "fix500k_w1e-4"), ("B", -5, "fix500k_w1e-5"), ("C", -6, "fix500k_w1e-6")]


def hists(path, names=("lth+", "lth-", "lthav")):
    H, cur = {}, None
    for line in open(path):
        w = line.split()
        if not w or w[0] == "xl":
            continue
        if w[0] == "Summed":
            cur = w[1] if w[1] in names else None
            if cur: H[cur] = []
            continue
        if cur:
            try: H[cur].append([float(x) for x in w[:4]])
            except ValueError: cur = None
    return {k: np.array(v) for k, v in H.items()}


def asym(h):
    w = h[:, 1] - h[:, 0]; s = h[:, 2] * w; e = h[:, 3] * w
    lo, hi = h[:, 1] <= 90, h[:, 0] >= 90
    B, F = s[lo].sum(), s[hi].sum(); T = B + F
    return (B - F) / T, 2 * np.hypot(F * np.sqrt((e[lo]**2).sum()), B * np.sqrt((e[hi]**2).sum())) / T**2


def fmt(v, e, nd):
    return f"{v:.{nd}f}({int(round(e * 10**nd))})"


res = {}
for tag, lw, run in RUNS:
    seeds = [d for d in glob.glob(f"{SC}/{run}/seed_*")
             if os.path.exists(d + "/done.txt") and os.path.getsize(d + "/NLOFF1.dat") > 0]
    if not seeds:
        continue
    sig = np.array([[float(x) for x in SIG.search(open(d + "/phokhara.out", errors="replace").read()).groups()] for d in seeds])
    H = {k: [] for k in ("lth+", "lth-", "lthav")}
    for d in seeds:
        h = hists(d + "/NLOFF1.dat")
        for k in H: H[k].append(h[k])
    A = {}
    for k in H:
        a = np.stack(H[k]); m = a[0].copy(); m[:, 2] = a[:, :, 2].mean(0); m[:, 3] = np.sqrt((a[:, :, 3]**2).sum(0)) / len(seeds)
        A[k] = asym(m)
    res[tag] = dict(lw=lw, run=run, n=len(seeds), sig=(sig[:, 0].mean(), np.sqrt((sig[:, 1]**2).sum()) / len(seeds)), A=A)

def mark(r):
    return "" if r["n"] >= 300 else f"$^{{[{r['n']}]}}$"

lines = ["% generated by make_numbers.py -- do not edit"]
summ = ["# fixed PHOKHARA (phokhara_fix = h1 + h3), 300 seeds x 500k per w; [n] = finished seeds if < 300"]
for tag, lw, run in RUNS:
    r = res.get(tag)
    if r is None:
        lines += [f"\\newcommand{{\\HiSig{tag}}}{{--}}", f"\\newcommand{{\\HiA{tag}}}{{--}}"]; continue
    lines += [f"\\newcommand{{\\HiSig{tag}}}{{{fmt(*r['sig'], 6)}{mark(r)}}}",
              f"\\newcommand{{\\HiA{tag}}}{{{fmt(*r['A']['lth+'], 5)}{mark(r)}}}"]
    summ.append(f"{run:15s} n={r['n']:3d} sigma_MC={fmt(*r['sig'], 6)}  A(th+)={fmt(*r['A']['lth+'], 5)}"
                f"  A(th-)={fmt(*r['A']['lth-'], 5)}  A(thav)={fmt(*r['A']['lthav'], 5)}")
if len(res) >= 2:
    lw = np.array([r["lw"] for r in res.values()])
    def fit(key, sign=1):
        y = np.array([sign * r["A"][key][0] for r in res.values()]); e = np.array([r["A"][key][1] for r in res.values()])
        m = np.sum(y / e**2) / np.sum(1 / e**2); me = 1 / np.sqrt(np.sum(1 / e**2))
        p, cov = np.polyfit(lw, y, 1, w=1 / e, cov="unscaled") if len(y) > 2 else (np.array([(y[1] - y[0]) / (lw[1] - lw[0]), 0]), np.array([[np.hypot(e[0], e[1])**2 / (lw[1] - lw[0])**2]]))
        return m, me, p[0], np.sqrt(cov[0, 0])
    m, me, sl, esl = fit("lth+"); mm, mme, _, _ = fit("lth-", -1); mv, mve, _, _ = fit("lthav", -1)
    lines += [f"\\newcommand{{\\HiSlope}}{{${sl:+.5f}\\pm{esl:.5f}$}}",
              f"\\newcommand{{\\HiAav}}{{{fmt(m, me, 5)}}}", f"\\newcommand{{\\HiAmav}}{{{fmt(mm, mme, 5)}}}",
              f"\\newcommand{{\\HiAvav}}{{{fmt(mv, mve, 5)}}}"]
    summ.append(f"slope dA(th+)/dlog10(w) = {sl:+.5f} +- {esl:.5f};  w-average A(th+) {fmt(m, me, 5)}, "
                f"-A(th-) {fmt(mm, mme, 5)}, -A(thav) {fmt(mv, mve, 5)}")
else:
    lines += ["\\newcommand{\\HiSlope}{--}", "\\newcommand{\\HiAav}{--}", "\\newcommand{\\HiAmav}{--}", "\\newcommand{\\HiAvav}{--}"]
summ.append("# CEEX prod500k (Emin 1e-4): A(th+) 0.23751(13), -A(th-) 0.23723(13), -A(thav) 0.26660(13); BabaYaga 0.23724 / 0.23727 / 0.26650")
open(os.path.join(HERE, "numbers.tex"), "w").write("\n".join(lines) + "\n")
os.makedirs(os.path.join(ROOT, "RESULTS", "fix500k"), exist_ok=True)
open(os.path.join(ROOT, "RESULTS", "fix500k", "summary.txt"), "w").write("\n".join(summ) + "\n")
print("\n".join(summ))
