#!/usr/bin/env python3
"""Write REPORT/numbers.tex: LaTeX macros with the high-statistics fixed-PHOKHARA results
(runs fix500k_w1e-4, fix500k_w1e-5, fix500k_w1e-6 under $PHOKHARA_SCRATCH;
appendix "Each fix alone": \\Scan* from runs fixscan_{none,h1,h3,both};
appendix KLOE-SA: \\Sa* from runs sa_nofix, sa_fix and PLOTS/DATA/kloe_sa_ref).

  \\HiSigA \\HiSigB \\HiSigC     sigma_MC per w (1e-4, 1e-5, 1e-6)
  \\HiAA   \\HiAB   \\HiAC       A(theta+) per w
  \\HiSlope                      fitted dA(theta+)/dlog10(w)
  \\HiAav \\HiAmav \\HiAvav      w-averaged A(theta+), -A(theta-), -A(thav)
Values of runs with fewer than 300 finished seeds are marked with their seed count.
Also writes RESULTS/fix500k/summary.txt.
"""
import glob, os, re, sys
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
SC = os.path.expanduser("~/scratch/CEEX_PHOKHARA_ANALYSIS/PHOKHARA")
SIG = re.compile(r"sigma_MC \(nbarn\)\s*=\s*(\S+)\s*\+-\s*(\S+)")
RUNS = [("A", -4, "fix500k_w1e-4"), ("B", -5, "fix500k_w1e-5"), ("C", -6, "fix500k_w1e-6")]


def hists(path, names=("lth+", "lth-", "lthav")):
    H, cur = {}, None
    for line in open(path):
        w = line.split()
        if not w or w[0] == "xl":
            continue
        if w[0] == "Summed":
            cur = w[1] if w[1] in names else None
            if cur: H[cur] = []
            continue
        if cur:
            try: H[cur].append([float(x) for x in w[:4]])
            except ValueError: cur = None
    return {k: np.array(v) for k, v in H.items()}


def asym(h):
    w = h[:, 1] - h[:, 0]; s = h[:, 2] * w; e = h[:, 3] * w
    lo, hi = h[:, 1] <= 90, h[:, 0] >= 90
    B, F = s[lo].sum(), s[hi].sum(); T = B + F
    return (B - F) / T, 2 * np.hypot(F * np.sqrt((e[lo]**2).sum()), B * np.sqrt((e[hi]**2).sum())) / T**2


def fmt(v, e, nd):
    return f"{v:.{nd}f}({int(round(e * 10**nd))})"


res = {}
for tag, lw, run in RUNS:
    seeds = [d for d in glob.glob(f"{SC}/{run}/seed_*")
             if os.path.exists(d + "/done.txt") and os.path.getsize(d + "/NLOFF1.dat") > 0]
    if not seeds:
        continue
    sig = np.array([[float(x) for x in SIG.search(open(d + "/phokhara.out", errors="replace").read()).groups()] for d in seeds])
    H = {k: [] for k in ("lth+", "lth-", "lthav")}
    for d in seeds:
        h = hists(d + "/NLOFF1.dat")
        for k in H: H[k].append(h[k])
    A = {}
    for k in H:
        a = np.stack(H[k]); m = a[0].copy(); m[:, 2] = a[:, :, 2].mean(0); m[:, 3] = np.sqrt((a[:, :, 3]**2).sum(0)) / len(seeds)
        A[k] = asym(m)
    res[tag] = dict(lw=lw, run=run, n=len(seeds), sig=(sig[:, 0].mean(), np.sqrt((sig[:, 1]**2).sum()) / len(seeds)), A=A)

def mark(r):
    return "" if r["n"] >= 300 else f"$^{{[{r['n']}]}}$"

lines = ["% generated by make_numbers.py -- do not edit"]
summ = ["# fixed PHOKHARA (phokhara_fix = h1 + h3), 300 seeds x 500k per w; [n] = finished seeds if < 300"]
for tag, lw, run in RUNS:
    r = res.get(tag)
    if r is None:
        lines += [f"\\newcommand{{\\HiSig{tag}}}{{--}}", f"\\newcommand{{\\HiA{tag}}}{{--}}"]; continue
    lines += [f"\\newcommand{{\\HiSig{tag}}}{{{fmt(*r['sig'], 6)}{mark(r)}}}",
              f"\\newcommand{{\\HiA{tag}}}{{{fmt(*r['A']['lth+'], 5)}{mark(r)}}}"]
    summ.append(f"{run:15s} n={r['n']:3d} sigma_MC={fmt(*r['sig'], 6)}  A(th+)={fmt(*r['A']['lth+'], 5)}"
                f"  A(th-)={fmt(*r['A']['lth-'], 5)}  A(thav)={fmt(*r['A']['lthav'], 5)}")
if len(res) >= 2:
    lw = np.array([r["lw"] for r in res.values()])
    def fit(key, sign=1):
        y = np.array([sign * r["A"][key][0] for r in res.values()]); e = np.array([r["A"][key][1] for r in res.values()])
        m = np.sum(y / e**2) / np.sum(1 / e**2); me = 1 / np.sqrt(np.sum(1 / e**2))
        p, cov = np.polyfit(lw, y, 1, w=1 / e, cov="unscaled") if len(y) > 2 else (np.array([(y[1] - y[0]) / (lw[1] - lw[0]), 0]), np.array([[np.hypot(e[0], e[1])**2 / (lw[1] - lw[0])**2]]))
        return m, me, p[0], np.sqrt(cov[0, 0])
    m, me, sl, esl = fit("lth+"); mm, mme, _, _ = fit("lth-", -1); mv, mve, _, _ = fit("lthav", -1)
    lines += [f"\\newcommand{{\\HiSlope}}{{${sl:+.5f}\\pm{esl:.5f}$}}",
              f"\\newcommand{{\\HiAav}}{{{fmt(m, me, 5)}}}", f"\\newcommand{{\\HiAmav}}{{{fmt(mm, mme, 5)}}}",
              f"\\newcommand{{\\HiAvav}}{{{fmt(mv, mve, 5)}}}"]
    summ.append(f"slope dA(th+)/dlog10(w) = {sl:+.5f} +- {esl:.5f};  w-average A(th+) {fmt(m, me, 5)}, "
                f"-A(th-) {fmt(mm, mme, 5)}, -A(thav) {fmt(mv, mve, 5)}")
else:
    lines += ["\\newcommand{\\HiSlope}{--}", "\\newcommand{\\HiAav}{--}", "\\newcommand{\\HiAmav}{--}", "\\newcommand{\\HiAvav}{--}"]
# the 1000 x 5M run at w = 1e-5 (\FiveN seeds, \FiveSig, \FiveA, \FiveAm, \FiveAv)
seeds5 = [d for d in glob.glob(f"{SC}/fix5M_w1e-5/seed_*")
          if os.path.exists(d + "/done.txt") and os.path.getsize(d + "/NLOFF1.dat") > 0]
if seeds5:
    sig = np.array([[float(x) for x in SIG.search(open(d + "/phokhara.out", errors="replace").read()).groups()] for d in seeds5])
    A5 = {}
    for k in ("lth+", "lth-", "lthav"):
        acc = None; acc2 = None
        for d in seeds5:   # running sums: 1000 x 600-bin histograms need not sit in memory
            h = hists(d + "/NLOFF1.dat", (k,))[k]
            acc = h.copy() if acc is None else acc + np.column_stack([0 * h[:, :2], h[:, 2:3], 0 * h[:, 3:]])
            acc2 = h[:, 3]**2 if acc2 is None else acc2 + h[:, 3]**2
        m = acc.copy(); m[:, 2] = acc[:, 2] / len(seeds5); m[:, 3] = np.sqrt(acc2) / len(seeds5)
        A5[k] = asym(m)
    s5 = (sig[:, 0].mean(), np.sqrt((sig[:, 1]**2).sum()) / len(seeds5))
    lines += [f"\\newcommand{{\\FiveN}}{{{len(seeds5)}}}", f"\\newcommand{{\\FiveSig}}{{{fmt(*s5, 6)}}}",
              f"\\newcommand{{\\FiveA}}{{{fmt(*A5['lth+'], 5)}}}",
              f"\\newcommand{{\\FiveAm}}{{{fmt(-A5['lth-'][0], A5['lth-'][1], 5)}}}",
              f"\\newcommand{{\\FiveAv}}{{{fmt(-A5['lthav'][0], A5['lthav'][1], 5)}}}"]
    summ.append(f"fix5M_w1e-5     n={len(seeds5):4d} sigma_MC={fmt(*s5, 6)}  A(th+)={fmt(*A5['lth+'], 5)}"
                f"  A(th-)={fmt(*A5['lth-'], 5)}  A(thav)={fmt(*A5['lthav'], 5)}")
else:
    lines += ["\\newcommand{\\FiveN}{--}", "\\newcommand{\\FiveSig}{--}", "\\newcommand{\\FiveA}{--}",
              "\\newcommand{\\FiveAm}{--}", "\\newcommand{\\FiveAv}{--}"]
# pion-angle shape chi2/ndf of the after-fix plots (RESULTS/final5M/summary.txt, table vs phokhara)
AFTER = "final5M_cfull_e5"   # after-fix plots: CEEX more1M full run (199/200 tasks, Emin 1e-5 only) vs fix5M PHOKHARA
sf = os.path.join(ROOT, "RESULTS", AFTER, "summary.txt")
chiC = chiB = "--"
if os.path.exists(sf):
    txt = open(sf).read().split("shape chi2/ndf vs phokhara", 1)
    if len(txt) == 2:
        rows = [l.split() for l in txt[1].split("\n\n", 1)[0].splitlines()[1:]]
        head = rows[0]; data = [r for r in rows[1:] if r and r[0] in ("lth+", "lth-", "lthav")]
        def col(name):
            j = 1 + 2 * (head.index(name) - 1)   # after "obs", each entry is "<chi2> (<ndf>)"
            return [float(r[j]) for r in data]
        c = sum((col(k) for k in ("ceex4", "ceex5") if k in head), []); b = col("babayaga")
        chiC = f"{min(c):.1f}--{max(c):.1f}"; chiB = f"{min(b):.1f}--{max(b):.1f}"
lines += [f"\\newcommand{{\\FiveChiC}}{{{chiC}}}", f"\\newcommand{{\\FiveChiB}}{{{chiB}}}"]
summ.append(f"{AFTER} pion-angle shape chi2/ndf: vs CEEX {chiC}, vs BabaYaga {chiB}")
# CEEX asymmetries of the after-fix run (\CeexN tasks, \CeexNr rank outputs, \CeexA/Am/Av/Sig at Emin 1e-5;
# \CeexFourA/Am/Av at Emin 1e-4)
def ceex_merged(path):
    H, cur = {}, None
    for line in open(path):
        if line.startswith(" Histogram:") or line.startswith("Histogram:"):
            cur = line.split("Histogram:")[1].strip(); H[cur] = []; continue
        if cur and line.split():
            try: H[cur].append([float(x) for x in line.split()[:4]])
            except ValueError: cur = None
    return {k: np.array(v) for k, v in H.items() if v}
cdir = os.path.join(ROOT, "PLOTS", "DATA", AFTER, "ceex")
CE = os.path.expanduser(f"~/scratch/CEEX_PHOKHARA_ANALYSIS/CEEX/{AFTER}")
for tag, ecut in (("", "5"), ("Four", "4")):
    f = os.path.join(cdir, f"merged_histograms_{ecut}.txt")
    if not os.path.exists(f):
        lines += [f"\\newcommand{{\\Ceex{tag}{k}}}{{--}}" for k in ("A", "Am", "Av")]; continue
    H = ceex_merged(f)
    a, am, av = asym(H["lth+"]), asym(H["lth-"]), asym(H["lthav"])
    w = H["lth+"][:, 1] - H["lth+"][:, 0]
    sg = ((H["lth+"][:, 2] * w).sum(), np.sqrt(((H["lth+"][:, 3] * w)**2).sum()))
    lines += [f"\\newcommand{{\\Ceex{tag}A}}{{{fmt(*a, 5)}}}", f"\\newcommand{{\\Ceex{tag}Am}}{{{fmt(-am[0], am[1], 5)}}}",
              f"\\newcommand{{\\Ceex{tag}Av}}{{{fmt(-av[0], av[1], 5)}}}", f"\\newcommand{{\\Ceex{tag}Sig}}{{{fmt(*sg, 6)}}}"]
    summ.append(f"CEEX {AFTER} Emin 1e-{ecut}: sigma={fmt(*sg, 6)}  A(th+)={fmt(*a, 5)}  -A(th-)={fmt(-am[0], am[1], 5)}  -A(thav)={fmt(-av[0], av[1], 5)}")
ntask = len(glob.glob(os.path.join(CE, "RUN_CEEX_*_5")))
nr = len(glob.glob(os.path.join(CE, "RUN_CEEX_*_5", "output_*.txt")))
lines += [f"\\newcommand{{\\CeexN}}{{{ntask}}}", f"\\newcommand{{\\CeexNr}}{{{nr}}}"]
summ.append("# CEEX prod500k (Emin 1e-4): A(th+) 0.23751(13), -A(th-) 0.23723(13), -A(thav) 0.26660(13); BabaYaga 0.23724 / 0.23727 / 0.26650")
# Appendix: each fix alone (runs fixscan_{none,h1,h3,both}: 300 x 500k, w = 1e-5, fresh seeds)
# \Scan{Sig,A,ChiC,ChiB,N}<tag>; ChiC/ChiB = lth+ shape chi2/ndf of CEEX / BabaYaga against
# that PHOKHARA, from RESULTS/fixscan_<v>/report/summary.txt
for tag, v in (("None", "none"), ("Hone", "h1"), ("Hthree", "h3"), ("Both", "both")):
    run = f"fixscan_{v}"
    seeds = [d for d in glob.glob(f"{SC}/{run}/seed_*")
             if os.path.exists(d + "/done.txt") and os.path.getsize(d + "/NLOFF1.dat") > 0]
    vals = dict(Sig="--", A="--", ChiC="--", ChiB="--", N=str(len(seeds)))
    if seeds:
        sig = np.array([[float(x) for x in SIG.search(open(d + "/phokhara.out", errors="replace").read()).groups()] for d in seeds])
        a = np.stack([hists(d + "/NLOFF1.dat", ("lth+",))["lth+"] for d in seeds])
        m = a[0].copy(); m[:, 2] = a[:, :, 2].mean(0); m[:, 3] = np.sqrt((a[:, :, 3]**2).sum(0)) / len(seeds)
        vals["Sig"] = fmt(sig[:, 0].mean(), np.sqrt((sig[:, 1]**2).sum()) / len(seeds), 6)
        vals["A"] = fmt(*asym(m), 5)
    sf = os.path.join(ROOT, "RESULTS", run, "report", "summary.txt")
    if os.path.exists(sf):
        txt = open(sf).read().split("shape chi2/ndf vs phokhara", 1)[1].split("\n\n", 1)[0].splitlines()
        head = txt[1].split(); row = next(l.split() for l in txt[2:] if l.split()[:1] == ["lth+"])
        vals["ChiC"] = row[1 + 2 * (head.index("ceex5") - 1)]; vals["ChiB"] = row[1 + 2 * (head.index("babayaga") - 1)]
    lines += [f"\\newcommand{{\\Scan{k}{tag}}}{{{x}}}" for k, x in vals.items()]
    summ.append(f"{run:15s} n={vals['N']:>4s} sigma_MC={vals['Sig']}  A(th+)={vals['A']}  lth+ chi2/ndf CEEX/PH {vals['ChiC']}, BY/PH {vals['ChiB']}")
# Appendix: KLOE-SA before/after the fix (runs sa_nofix, sa_fix: 300 x 1M, w = 1e-5) and the SA
# references in PLOTS/DATA/kloe_sa_ref. \Sa{Sig,A,Am,Av}{Nofix,Fix,BB,Ceex}; \SaD{Sig,A,Am,Av}: fixed - unpatched
# (with pull); \SaDodd: C-odd shift [dA(th+) - dA(th-)]/2. Am, Av are A(theta-), A(theta_avg), not negated.
NUM = r"([-+]?\d+\.\d*(?:[EeDd][-+]?\d+)?)"
SIGSA = re.compile(r"sigma_MC \(nbarn\)\s*=?\s*" + NUM + r"\s+\+-\s+" + NUM + r"\s*$", re.M)   # lines can interleave
def asym_range(lo, hi, y, e):
    w = hi - lo; m = (lo >= 50 - 1e-9) & (hi <= 130 + 1e-9)
    return asym(np.column_stack([lo, hi, y, e])[m])
sa = {}
for tag, run in (("Nofix", "sa_nofix"), ("Fix", "sa_fix")):
    seeds = [d for d in glob.glob(f"{SC}/{run}/seed_*")
             if os.path.exists(d + "/done.txt") and os.path.getsize(d + "/NLOFF1.dat") > 0]
    if not seeds:
        continue
    sig = np.array([[float(x) for x in SIGSA.findall(open(d + "/phokhara.out", errors="replace").read())[-1]] for d in seeds])
    H = {k: [] for k in ("lth+", "lth-", "lthav")}
    for d in seeds:
        h = hists(d + "/NLOFF1.dat")
        for k in H: H[k].append(h[k])
    A = {}
    for k in H:
        a = np.stack(H[k]); m = a[0].copy(); m[:, 2] = a[:, :, 2].mean(0); m[:, 3] = np.sqrt((a[:, :, 3]**2).sum(0)) / len(seeds)
        A[k] = asym(m)
    sa[tag] = dict(n=len(seeds), sig=(sig[:, 0].mean(), np.sqrt((sig[:, 1]**2).sum()) / len(seeds)), A=A)
REF = os.path.join(ROOT, "PLOTS", "DATA", "kloe_sa_ref")
if os.path.isdir(REF):
    A = {}
    for k in ("th+", "th-", "thav"):
        b = np.loadtxt(f"{REF}/babayaga/BB_s{k}.txt", delimiter=",", skiprows=1); dx = b[1, 0] - b[0, 0]
        A["l" + k] = asym_range(b[:, 0], b[:, 0] + dx, b[:, 1], b[:, 2])
    w = dx * b[:, 1]; m = (b[:, 0] >= 50 - 1e-9) & (b[:, 0] + dx <= 130 + 1e-9)
    sa["BB"] = dict(sig=(w[m].sum(), np.sqrt(((dx * b[:, 2])[m]**2).sum())), A=A)
    Hc = ceex_merged(f"{REF}/ceex/merged_histograms_5.txt"); A = {}
    for k in ("th+", "th-", "thav"):
        c = Hc["s" + k]; A["l" + k] = asym_range(c[:, 0], c[:, 1], c[:, 2], c[:, 3])
    c = Hc["sth+"]; sa["Ceex"] = dict(sig=((c[:, 2] * (c[:, 1] - c[:, 0])).sum(), np.sqrt(((c[:, 3] * (c[:, 1] - c[:, 0]))**2).sum())), A=A)
for tag, r in sa.items():
    lines += [f"\\newcommand{{\\SaSig{tag}}}{{{fmt(*r['sig'], 5)}}}"]
    lines += [f"\\newcommand{{\\Sa{m}{tag}}}{{{fmt(*r['A'][k], 5)}}}" for m, k in (("A", "lth+"), ("Am", "lth-"), ("Av", "lthav"))]
    summ.append(f"KLOE-SA {tag:5s} n={r.get('n', '-')} sigma={fmt(*r['sig'], 5)} A(th+)={fmt(*r['A']['lth+'], 5)} "
                f"A(th-)={fmt(*r['A']['lth-'], 5)} A(thav)={fmt(*r['A']['lthav'], 5)}")
def dfmt(a, b, nd=5):
    d, e = a[0] - b[0], np.hypot(a[1], b[1])
    return f"${d:+.{nd}f}({int(round(e * 10**nd))})$, ${abs(d) / e:.1f}\\sigma$"
if "Fix" in sa and "Nofix" in sa:
    f, u = sa["Fix"], sa["Nofix"]
    lines += [f"\\newcommand{{\\SaDSig}}{{{dfmt(f['sig'], u['sig'])}}}"]
    lines += [f"\\newcommand{{\\SaD{m}}}{{{dfmt(f['A'][k], u['A'][k])}}}" for m, k in (("A", "lth+"), ("Am", "lth-"), ("Av", "lthav"))]
    dp = f["A"]["lth+"][0] - u["A"]["lth+"][0]; dm = f["A"]["lth-"][0] - u["A"]["lth-"][0]
    eo = np.hypot(np.hypot(f["A"]["lth+"][1], u["A"]["lth+"][1]), np.hypot(f["A"]["lth-"][1], u["A"]["lth-"][1])) / 2
    lines += [f"\\newcommand{{\\SaDodd}}{{{(dp - dm) / 2:+.5f}({int(round(eo * 1e5))})}}"]
    summ.append(f"KLOE-SA fixed-unpatched: sigma {dfmt(f['sig'], u['sig'])}; C-odd shift {(dp - dm) / 2:+.5f}({int(round(eo * 1e5))})")
open(os.path.join(HERE, "numbers.tex"), "w").write("\n".join(lines) + "\n")
os.makedirs(os.path.join(ROOT, "RESULTS", "fix500k"), exist_ok=True)
open(os.path.join(ROOT, "RESULTS", "fix500k", "summary.txt"), "w").write("\n".join(summ) + "\n")
print("\n".join(summ))
